### ISSUE TITLE
Error on Make

### ISSUE THREAD

**Issue by enforce1** [djpohly/piuio#12]
Hey there, DJ,

Making the module, getting errors on make... I may be dumb, and if this is a dumb question, sorry in advance. Linux mint 13 32-bit, on an MK7 with 2 GB ram:

pump@pump-desktop ~/PIUIO/piuio-master/mod $ make
make -C /lib/modules/3.2.0-23-generic/build M=/home/pump/PIUIO/piuio-master/mod modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-23-generic'
  CC [M]  /home/pump/PIUIO/piuio-master/mod/piuio.o
/home/pump/PIUIO/piuio-master/mod/piuio.c: In function ‘piuio_close’:
/home/pump/PIUIO/piuio-master/mod/piuio.c:337:2: error: implicit declaration of function ‘usb_block_urb’ [-Werror=implicit-function-declaration]
/home/pump/PIUIO/piuio-master/mod/piuio.c:343:2: error: implicit declaration of function ‘usb_unblock_urb’ [-Werror=implicit-function-declaration]
/home/pump/PIUIO/piuio-master/mod/piuio.c: In function ‘piuio_leds_init’:
/home/pump/PIUIO/piuio-master/mod/piuio.c:438:39: error: ‘struct class’ has no member named ‘dev_groups’
/home/pump/PIUIO/piuio-master/mod/piuio.c: At top level:
/home/pump/PIUIO/piuio-master/mod/piuio.c:645:1: warning: data definition has no type or storage class [enabled by default]
/home/pump/PIUIO/piuio-master/mod/piuio.c:645:1: warning: type defaults to ‘int’ in declaration of ‘module_usb_driver’ [-Wimplicit-int]
/home/pump/PIUIO/piuio-master/mod/piuio.c:645:1: warning: parameter names (without types) in function declaration [enabled by default]
/home/pump/PIUIO/piuio-master/mod/piuio.c:633:26: warning: ‘piuio_driver’ defined but not used [-Wunused-variable]
cc1: some warnings being treated as errors
make[2]: *** [/home/pump/PIUIO/piuio-master/mod/piuio.o] Error 1
make[1]: *** [_module_/home/pump/PIUIO/piuio-master/mod] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-23-generic'
make: *** [modules] Error 2

**Comment by djpohly** [comment]
Hi enforce1 - looks like you're on a kernel version from over three years ago (3.2.0), so try checking out the `legacy` branch instead of `master`.  Main development follows the current kernel (though it should work on anything since kernel 3.11).

Upgrading to a newer release of Mint would be another solution, if that's an option.

**Comment by enforce1** [comment]
Totally fine, I was following a guide taht recommended using it, I'll grab the latest and greatest right away!
